# Handles the definition of the HL7 segments
class hl7Segment(object):
	def __init__(self, code, description):
		self.code = code
		self.description = description
		self.fields = {}

	# Gets a segment object based on his code. If no object is found in the segmentList with the following code None is returned.
	def getSegmentByCode(self, code, segmentList):
		for listItem in segmentList:
			if (listItem.code == code):
				return listItem
		return None

	# Gets a segment and fields data based on version number
	def getSegmentDefinition(self, version):
		with open(f'./definitions/{version}.json', 'r') as file:
			self.fields = json.load(file)

	# Loads the entire segment list
	def loadSegmentList(self):
		hl7SegmentList = []

		hl7SegmentList.append(hl7Segment("ABS", "Abstract").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ACC", "Accident").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ADD", "Addendum").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ADJ", "Adjustment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AFF", "Professional Affiliation").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AIG", "Appointment Information - General Resource").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AIL", "Appointment Information - Location Resource").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AIP", "Appointment Information - Personnel Resource").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AIS", "Appointment Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AL1", "Patient Allergy Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("APR", "Appointment Preferences").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ARQ", "Appointment Request").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ARV", "Access Restriction").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("AUT", "Authorization Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BHS", "Batch Header").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BLC", "Blood Code").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BLG", "Billing").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BPO", "Blood product order").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BPX", "Blood product dispense status").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BTS", "Batch Trailer").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BTX", "Blood Product Transfusion/Disposition").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("BUI", "Blood Unit Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CDM", "Charge Description Master").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CDO", "Cumulative Dosage").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CER", "Certificate Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CM0", "Clinical Study Master").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CM1", "Clinical Study Phase Master").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CM2", "Clinical Study Schedule Master").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CNS", "Clear Notification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CON", "Consent Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CSP", "Clinical Study Phase").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CSR", "Clinical Study Registration").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CSS", "Clinical Study Data Schedule Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CTD", "Contact Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("CTI", "Clinical Trial Identification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DB1", "Disability").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DG1", "Diagnosis").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DMI", "DRG Master File Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DON", "Donation").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DRG", "Diagnosis Related Group").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DSC", "Continuation Pointer").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("DSP", "Display Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ECD", "Equipment Command").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ECR", "Equipment Command Response").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("EDU", "Educational Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("EQP", "Equipment/log Service").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("EQU", "Equipment Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ERR", "Error").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("EVN", "Event Type").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("FAC", "Facility").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("FHS", "File Header").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("FT1", "Financial Transaction").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("FTS", "File Trailer").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("GOL", "Goal Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("GP1", "Grouping/Reimbursement - Visit").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("GP2", "Grouping/Reimbursement - Procedure Line Item").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("GT1", "Guarantor").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("Hxx", "any HL7 segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IAM", "Patient Adverse Reaction Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IAR", "Allergy Reaction").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IIM", "Inventory Item Master").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ILT", "Material Lot").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IN1", "Insurance").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IN2", "Insurance Additional Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IN3", "Insurance Additional Information, Certification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("INV", "Inventory Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IPC", "Imaging Procedure Control Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IPR", "Invoice Processing Results").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ISD", "Interaction Status Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ITM", "Material Item").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IVC", "Invoice Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("IVT", "Material Location").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("LAN", "Language Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("LCC", "Location Charge Code").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("LCH", "Location Characteristic").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("LDP", "Location Department").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("LOC", "Location Identification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("LRL", "Location Relationship").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("MFA", "Master File Acknowledgment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("MFE", "Master File Entry").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("MFI", "Master File Identification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("MRG", "Merge Patient Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("MSA", "Message Acknowledgment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("MSH", "Message Header").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NCK", "System Clock").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NDS", "Notification Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NK1", "Next of Kin / Associated Parties").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NPU", "Bed Status Update").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NSC", "Application Status Change").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NST", "Application control level statistics").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("NTE", "Notes and Comments").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OBR", "Observation Request").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OBX", "Observation/Result").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ODS", "Dietary Orders, Supplements, and Preferences").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ODT", "Diet Tray Instructions").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM1", "General Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM2", "Numeric Observation").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM3", "Categorical Service/Test/Observation").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM4", "Observations that Require Specimens").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM5", "Observation Batteries (Sets)").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM6", "Observations that are Calculated from Other Observations").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OM7", "Additional Basic Attributes").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OMC", "Supporting Clinical Information Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OMP", "Pharmacy/Treatment Order Message").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ORC", "Common Order").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ORG", "Practitioner Organization Unit").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ORP", "Pharmacy/Treatment Order Acknowledgment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("OVR", "Override Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PAC", "Shipment Package").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PCE", "Patient Charge Cost Center Exceptions").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PCR", "Possible Causal Relationship").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PD1", "Patient Additional Demographic").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PDA", "Patient Death and Autopsy").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PDC", "Product Detail Country").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PEO", "Product Experience Observation").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PES", "Product Experience Sender").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PID", "Patient Identification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PKG", "Item Packaging").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PM1", "Payer Master File Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PMT", "Payment Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PR1", "Procedures").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PRA", "Practitioner Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PRB", "Problem Details").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PRC", "Pricing").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PRD", "Provider Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PRT", "Participation Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PSG", "Product/Service Group").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PSH", "Product Summary Header").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PSL", "Product/Service Line Item").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PSS", "Product/Service Section").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PTH", "Pathway").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PV1", "Patient Visit").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PV2", "Patient Visit - Additional Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("PYE", "Payee Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("QAK", "Query Acknowledgment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("QID", "Query Identification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("QPD", "Query Parameter Definition").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("QRD", "Original-Style Query Definition").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("QRF", "Original style query filter").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("QRI", "Query Response Instance").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RCP", "Response Control Parameter").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RDF", "Table Row Definition").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RDT", "Table Row Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("REL", "Clinical Relationship Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RF1", "Referral Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RFI", "Request for Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RGS", "Resource Group").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RMI", "Risk Management Incident").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ROL", "Role").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RQ1", "Requisition Detail-1").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RQD", "Requisition Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RRD", "Pharmacy/Treatment Dispense Acknowledgement").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXA", "Pharmacy/Treatment Administration").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXC", "Pharmacy/Treatment Component Order").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXD", "Pharmacy/Treatment Dispense").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXE", "Pharmacy/Treatment Encoded Order").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXG", "Pharmacy/Treatment Give").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXO", "Pharmacy/Treatment Order").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXR", "Pharmacy/Treatment Route").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("RXV", "Pharmacy/Treatment Infusion").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SAC", "Specimen Container detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SCD", "Anti-Microbial Cycle Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SCH", "Scheduling Activity Information").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SCP", "Sterilizer Configuration (Anti-Microbial Devices)").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SDD", "Sterilization Device Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SFT", "Software Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SGH", "Segment Group Header").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SGT", "Segment Group Trailer").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SHP", "Shipment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SID", "Substance Identifier").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SLT", "Sterilization Lot").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("SPM", "Specimen").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("STF", "Staff Identification").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("STZ", "Sterilization Parameter").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("TCC", "Test Code Configuration").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("TCD", "Test Code Detail").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("TQ1", "Timing/Quantity").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("TQ2", "Timing/Quantity Relationship").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("TXA", "Transcription Document Header").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("UAC", "User Authentication Credential Segment").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("UB1", "UB82 Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("UB2", "Uniform Billing Data").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("URD", "Results/update Definition").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("URS", "Unsolicited Selection").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("VAR", "Variance").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("VND", "Purchasing Vendor").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("ZL7", "(This is a proposed example only)").getSegmentDefinition("2.3.1"))
		hl7SegmentList.append(hl7Segment("Zxx", "Any Z-Segment").getSegmentDefinition("2.3.1"))

		return hl7SegmentList